version: "3"

services:
  backend:
    image: everyhealthdev/everyhealth-backend
    container_name: backend
    hostname: backend
    env_file:
      - .env
    expose:
      - "8080"

  nginx:
    image: everyhealthdev/everyhealth-nginx
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"