spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        database-platform: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 1000

jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  accesstoken-validity-in-seconds: 86400
  refreshtoken-validity-in-seconds: 1209600

server:
  url: ${SERVER_URL}

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace