spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: true


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace